### ISSUE TITLE
Negative Width error

### ISSUE THREAD

**Issue by therealccarter** [zagum/Android-ExpandIcon#5]
XML: 

        <com.github.zagum.expandicon.ExpandIconView
                        android:layout_width="match_parent"
                        android:layout_height="50dp"
          />

Stack trace:

    java.lang.IllegalArgumentException: negative width
	at java.awt.BasicStroke.<init>(BasicStroke.java:194)
	at java.awt.BasicStroke.<init>(BasicStroke.java:249)
	at android.graphics.Paint_Delegate.getJavaStroke(Paint_Delegate.java:205)
	at com.android.layoutlib.bridge.impl.GcSnapshot.createCustomGraphics(GcSnapshot.java:788)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawInLayer(GcSnapshot.java:613)
	at com.android.layoutlib.bridge.impl.GcSnapshot.draw(GcSnapshot.java:583)
	at android.graphics.Canvas_Delegate.draw(Canvas_Delegate.java:1032)
	at android.graphics.Canvas_Delegate.native_drawPath(Canvas_Delegate.java:713)
	at android.graphics.Canvas.native_drawPath(Canvas.java)
	at android.graphics.Canvas.drawPath(Canvas.java:1262)
	at com.github.zagum.expandicon.ExpandIconView.onDraw_Original(ExpandIconView.java:199)
	at com.github.zagum.expandicon.ExpandIconView.onDraw(ExpandIconView.java)
	at android.view.View.draw(View.java:17068)
	at android.view.View.draw(View.java:16976)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at android.widget.ScrollView.draw(ScrollView.java:1722)
	at android.view.View.draw(View.java:16976)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at android.view.View.draw(View.java:16976)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:505)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:87)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$71(RenderTask.java:698)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zagum** [comment]
Is this error only in edit mode ?

**Comment by zagum** [comment]
Thanks for report!
Fix will be in v. 1.1.1
